package com.bawei.hujintao.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.hujintao.model.bean.SqLeftBean;
import com.bawei.hujintao.model.bean.SqRightBean;

import com.bawei.hujintao.database.SqLeftBeanDao;
import com.bawei.hujintao.database.SqRightBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sqLeftBeanDaoConfig;
    private final DaoConfig sqRightBeanDaoConfig;

    private final SqLeftBeanDao sqLeftBeanDao;
    private final SqRightBeanDao sqRightBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sqLeftBeanDaoConfig = daoConfigMap.get(SqLeftBeanDao.class).clone();
        sqLeftBeanDaoConfig.initIdentityScope(type);

        sqRightBeanDaoConfig = daoConfigMap.get(SqRightBeanDao.class).clone();
        sqRightBeanDaoConfig.initIdentityScope(type);

        sqLeftBeanDao = new SqLeftBeanDao(sqLeftBeanDaoConfig, this);
        sqRightBeanDao = new SqRightBeanDao(sqRightBeanDaoConfig, this);

        registerDao(SqLeftBean.class, sqLeftBeanDao);
        registerDao(SqRightBean.class, sqRightBeanDao);
    }
    
    public void clear() {
        sqLeftBeanDaoConfig.clearIdentityScope();
        sqRightBeanDaoConfig.clearIdentityScope();
    }

    public SqLeftBeanDao getSqLeftBeanDao() {
        return sqLeftBeanDao;
    }

    public SqRightBeanDao getSqRightBeanDao() {
        return sqRightBeanDao;
    }

}
